// GENERATED CODE -- DO NOT EDIT!
// Generated by scripts/generate-protobus-setup.mjs
import * as proto from "@shared/proto/index"
export { IsaacError, IsaacErrorType } from "@/../../src/services/error/IsaacError"
import { ProtoBusClient, Callbacks } from "./grpc-client-base"

export class BrowserServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.BrowserService"
    static async getBrowserConnectionInfo(request: proto.isaac.EmptyRequest): Promise<proto.isaac.BrowserConnectionInfo> {
		return this.makeUnaryRequest("getBrowserConnectionInfo", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.BrowserConnectionInfo.fromJSON)
	}
    static async testBrowserConnection(request: proto.isaac.StringRequest): Promise<proto.isaac.BrowserConnection> {
		return this.makeUnaryRequest("testBrowserConnection", request, proto.isaac.StringRequest.toJSON, proto.isaac.BrowserConnection.fromJSON)
	}
    static async discoverBrowser(request: proto.isaac.EmptyRequest): Promise<proto.isaac.BrowserConnection> {
		return this.makeUnaryRequest("discoverBrowser", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.BrowserConnection.fromJSON)
	}
    static async getDetectedChromePath(request: proto.isaac.EmptyRequest): Promise<proto.isaac.ChromePath> {
		return this.makeUnaryRequest("getDetectedChromePath", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.ChromePath.fromJSON)
	}
    static async relaunchChromeDebugMode(request: proto.isaac.EmptyRequest): Promise<proto.isaac.String> {
		return this.makeUnaryRequest("relaunchChromeDebugMode", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.String.fromJSON)
	}
}
export class CheckpointsServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.CheckpointsService"
    static async checkpointDiff(request: proto.isaac.Int64Request): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("checkpointDiff", request, proto.isaac.Int64Request.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async checkpointRestore(request: proto.isaac.CheckpointRestoreRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("checkpointRestore", request, proto.isaac.CheckpointRestoreRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static subscribeToCheckpoints(request: proto.isaac.CheckpointSubscriptionRequest, callbacks: Callbacks<proto.isaac.CheckpointEvent>): ()=>void {
		return this.makeStreamingRequest("subscribeToCheckpoints", request, proto.isaac.CheckpointSubscriptionRequest.toJSON, proto.isaac.CheckpointEvent.fromJSON, callbacks)
	}
    static async getCwdHash(request: proto.isaac.StringArrayRequest): Promise<proto.isaac.PathHashMap> {
		return this.makeUnaryRequest("getCwdHash", request, proto.isaac.StringArrayRequest.toJSON, proto.isaac.PathHashMap.fromJSON)
	}
}
export class CommandsServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.CommandsService"
    static async addToIsaac(request: proto.isaac.CommandContext): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("addToIsaac", request, proto.isaac.CommandContext.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async fixWithIsaac(request: proto.isaac.CommandContext): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("fixWithIsaac", request, proto.isaac.CommandContext.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async explainWithIsaac(request: proto.isaac.CommandContext): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("explainWithIsaac", request, proto.isaac.CommandContext.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async improveWithIsaac(request: proto.isaac.CommandContext): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("improveWithIsaac", request, proto.isaac.CommandContext.toJSON, proto.isaac.Empty.fromJSON)
	}
}
export class FileServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.FileService"
    static async copyToClipboard(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("copyToClipboard", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async openFile(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("openFile", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async openImage(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("openImage", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async openMention(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("openMention", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async deleteRuleFile(request: proto.isaac.RuleFileRequest): Promise<proto.isaac.RuleFile> {
		return this.makeUnaryRequest("deleteRuleFile", request, proto.isaac.RuleFileRequest.toJSON, proto.isaac.RuleFile.fromJSON)
	}
    static async createRuleFile(request: proto.isaac.RuleFileRequest): Promise<proto.isaac.RuleFile> {
		return this.makeUnaryRequest("createRuleFile", request, proto.isaac.RuleFileRequest.toJSON, proto.isaac.RuleFile.fromJSON)
	}
    static async searchCommits(request: proto.isaac.StringRequest): Promise<proto.isaac.GitCommits> {
		return this.makeUnaryRequest("searchCommits", request, proto.isaac.StringRequest.toJSON, proto.isaac.GitCommits.fromJSON)
	}
    static async selectFiles(request: proto.isaac.BooleanRequest): Promise<proto.isaac.StringArrays> {
		return this.makeUnaryRequest("selectFiles", request, proto.isaac.BooleanRequest.toJSON, proto.isaac.StringArrays.fromJSON)
	}
    static async getRelativePaths(request: proto.isaac.RelativePathsRequest): Promise<proto.isaac.RelativePaths> {
		return this.makeUnaryRequest("getRelativePaths", request, proto.isaac.RelativePathsRequest.toJSON, proto.isaac.RelativePaths.fromJSON)
	}
    static async searchFiles(request: proto.isaac.FileSearchRequest): Promise<proto.isaac.FileSearchResults> {
		return this.makeUnaryRequest("searchFiles", request, proto.isaac.FileSearchRequest.toJSON, proto.isaac.FileSearchResults.fromJSON)
	}
    static async toggleIsaacRule(request: proto.isaac.ToggleIsaacRuleRequest): Promise<proto.isaac.ToggleIsaacRules> {
		return this.makeUnaryRequest("toggleIsaacRule", request, proto.isaac.ToggleIsaacRuleRequest.toJSON, proto.isaac.ToggleIsaacRules.fromJSON)
	}
    static async toggleCursorRule(request: proto.isaac.ToggleCursorRuleRequest): Promise<proto.isaac.IsaacRulesToggles> {
		return this.makeUnaryRequest("toggleCursorRule", request, proto.isaac.ToggleCursorRuleRequest.toJSON, proto.isaac.IsaacRulesToggles.fromJSON)
	}
    static async toggleWindsurfRule(request: proto.isaac.ToggleWindsurfRuleRequest): Promise<proto.isaac.IsaacRulesToggles> {
		return this.makeUnaryRequest("toggleWindsurfRule", request, proto.isaac.ToggleWindsurfRuleRequest.toJSON, proto.isaac.IsaacRulesToggles.fromJSON)
	}
    static async toggleAgentsRule(request: proto.isaac.ToggleAgentsRuleRequest): Promise<proto.isaac.IsaacRulesToggles> {
		return this.makeUnaryRequest("toggleAgentsRule", request, proto.isaac.ToggleAgentsRuleRequest.toJSON, proto.isaac.IsaacRulesToggles.fromJSON)
	}
    static async refreshRules(request: proto.isaac.EmptyRequest): Promise<proto.isaac.RefreshedRules> {
		return this.makeUnaryRequest("refreshRules", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.RefreshedRules.fromJSON)
	}
    static async openDiskConversationHistory(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("openDiskConversationHistory", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async toggleWorkflow(request: proto.isaac.ToggleWorkflowRequest): Promise<proto.isaac.IsaacRulesToggles> {
		return this.makeUnaryRequest("toggleWorkflow", request, proto.isaac.ToggleWorkflowRequest.toJSON, proto.isaac.IsaacRulesToggles.fromJSON)
	}
    static async ifFileExistsRelativePath(request: proto.isaac.StringRequest): Promise<proto.isaac.BooleanResponse> {
		return this.makeUnaryRequest("ifFileExistsRelativePath", request, proto.isaac.StringRequest.toJSON, proto.isaac.BooleanResponse.fromJSON)
	}
    static async openFileRelativePath(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("openFileRelativePath", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async refreshHooks(request: proto.isaac.EmptyRequest): Promise<proto.isaac.HooksToggles> {
		return this.makeUnaryRequest("refreshHooks", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.HooksToggles.fromJSON)
	}
    static async toggleHook(request: proto.isaac.ToggleHookRequest): Promise<proto.isaac.ToggleHookResponse> {
		return this.makeUnaryRequest("toggleHook", request, proto.isaac.ToggleHookRequest.toJSON, proto.isaac.ToggleHookResponse.fromJSON)
	}
    static async createHook(request: proto.isaac.CreateHookRequest): Promise<proto.isaac.CreateHookResponse> {
		return this.makeUnaryRequest("createHook", request, proto.isaac.CreateHookRequest.toJSON, proto.isaac.CreateHookResponse.fromJSON)
	}
    static async deleteHook(request: proto.isaac.DeleteHookRequest): Promise<proto.isaac.DeleteHookResponse> {
		return this.makeUnaryRequest("deleteHook", request, proto.isaac.DeleteHookRequest.toJSON, proto.isaac.DeleteHookResponse.fromJSON)
	}
    static async refreshSkills(request: proto.isaac.EmptyRequest): Promise<proto.isaac.RefreshedSkills> {
		return this.makeUnaryRequest("refreshSkills", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.RefreshedSkills.fromJSON)
	}
    static async toggleSkill(request: proto.isaac.ToggleSkillRequest): Promise<proto.isaac.SkillsToggles> {
		return this.makeUnaryRequest("toggleSkill", request, proto.isaac.ToggleSkillRequest.toJSON, proto.isaac.SkillsToggles.fromJSON)
	}
    static async createSkillFile(request: proto.isaac.CreateSkillRequest): Promise<proto.isaac.SkillsToggles> {
		return this.makeUnaryRequest("createSkillFile", request, proto.isaac.CreateSkillRequest.toJSON, proto.isaac.SkillsToggles.fromJSON)
	}
    static async deleteSkillFile(request: proto.isaac.DeleteSkillRequest): Promise<proto.isaac.SkillsToggles> {
		return this.makeUnaryRequest("deleteSkillFile", request, proto.isaac.DeleteSkillRequest.toJSON, proto.isaac.SkillsToggles.fromJSON)
	}
}
export class ModelsServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.ModelsService"
    static async getLmStudioModels(request: proto.isaac.StringRequest): Promise<proto.isaac.StringArray> {
		return this.makeUnaryRequest("getLmStudioModels", request, proto.isaac.StringRequest.toJSON, proto.isaac.StringArray.fromJSON)
	}
    static async getVsCodeLmModels(request: proto.isaac.EmptyRequest): Promise<proto.isaac.VsCodeLmModelsArray> {
		return this.makeUnaryRequest("getVsCodeLmModels", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.VsCodeLmModelsArray.fromJSON)
	}
    static async refreshOpenRouterModelsRpc(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshOpenRouterModelsRpc", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshIsaacModelsRpc(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshIsaacModelsRpc", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshHuggingFaceModels(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshHuggingFaceModels", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshOpenAiModels(request: proto.isaac.OpenAiModelsRequest): Promise<proto.isaac.StringArray> {
		return this.makeUnaryRequest("refreshOpenAiModels", request, proto.isaac.OpenAiModelsRequest.toJSON, proto.isaac.StringArray.fromJSON)
	}
    static async refreshRequestyModels(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshRequestyModels", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshLiteLlmModelsRpc(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshLiteLlmModelsRpc", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static subscribeToOpenRouterModels(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.OpenRouterCompatibleModelInfo>): ()=>void {
		return this.makeStreamingRequest("subscribeToOpenRouterModels", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON, callbacks)
	}
    static subscribeToLiteLlmModels(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.OpenRouterCompatibleModelInfo>): ()=>void {
		return this.makeStreamingRequest("subscribeToLiteLlmModels", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON, callbacks)
	}
    static async updateApiConfigurationProto(request: proto.isaac.UpdateApiConfigurationRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateApiConfigurationProto", request, proto.isaac.UpdateApiConfigurationRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateApiConfiguration(request: proto.isaac.UpdateApiConfigurationRequestNew): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateApiConfiguration", request, proto.isaac.UpdateApiConfigurationRequestNew.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateApiConfigurationPartial(request: proto.isaac.UpdateApiConfigurationPartialRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateApiConfigurationPartial", request, proto.isaac.UpdateApiConfigurationPartialRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async authenticateOpenAiCodex(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("authenticateOpenAiCodex", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async signOutOpenAiCodex(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("signOutOpenAiCodex", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async refreshGroqModelsRpc(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshGroqModelsRpc", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshBasetenModelsRpc(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshBasetenModelsRpc", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async getAihubmixModels(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("getAihubmixModels", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
    static async refreshVercelAiGatewayModelsRpc(request: proto.isaac.EmptyRequest): Promise<proto.isaac.OpenRouterCompatibleModelInfo> {
		return this.makeUnaryRequest("refreshVercelAiGatewayModelsRpc", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.OpenRouterCompatibleModelInfo.fromJSON)
	}
}
export class SlashServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.SlashService"
    static async reportBug(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("reportBug", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async condense(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("condense", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async getAvailableSlashCommands(request: proto.isaac.EmptyRequest): Promise<proto.isaac.SlashCommandsResponse> {
		return this.makeUnaryRequest("getAvailableSlashCommands", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.SlashCommandsResponse.fromJSON)
	}
}
export class StackServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.StackService"
    static async getStackSnapshot(request: proto.isaac.EmptyRequest): Promise<proto.isaac.StackSnapshot> {
		return this.makeUnaryRequest("getStackSnapshot", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.StackSnapshot.fromJSON)
	}
    static async startStack(request: proto.isaac.EmptyRequest): Promise<proto.isaac.StackActionResult> {
		return this.makeUnaryRequest("startStack", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.StackActionResult.fromJSON)
	}
    static async stopStack(request: proto.isaac.EmptyRequest): Promise<proto.isaac.StackActionResult> {
		return this.makeUnaryRequest("stopStack", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.StackActionResult.fromJSON)
	}
    static async restartStack(request: proto.isaac.EmptyRequest): Promise<proto.isaac.StackActionResult> {
		return this.makeUnaryRequest("restartStack", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.StackActionResult.fromJSON)
	}
    static async setUseLocalStack(request: proto.isaac.BooleanRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("setUseLocalStack", request, proto.isaac.BooleanRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async setEnabledMcpServers(request: proto.isaac.StringArrayRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("setEnabledMcpServers", request, proto.isaac.StringArrayRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async setMcpToolDenylist(request: proto.isaac.StringArrayRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("setMcpToolDenylist", request, proto.isaac.StringArrayRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async setMcpToolAllowlist(request: proto.isaac.StringArrayRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("setMcpToolAllowlist", request, proto.isaac.StringArrayRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateJinaRoutes(request: proto.isaac.UpdateJinaRoutesRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateJinaRoutes", request, proto.isaac.UpdateJinaRoutesRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
}
export class StateServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.StateService"
    static async getLatestState(request: proto.isaac.EmptyRequest): Promise<proto.isaac.State> {
		return this.makeUnaryRequest("getLatestState", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.State.fromJSON)
	}
    static async updateTerminalConnectionTimeout(request: proto.isaac.UpdateTerminalConnectionTimeoutRequest): Promise<proto.isaac.UpdateTerminalConnectionTimeoutResponse> {
		return this.makeUnaryRequest("updateTerminalConnectionTimeout", request, proto.isaac.UpdateTerminalConnectionTimeoutRequest.toJSON, proto.isaac.UpdateTerminalConnectionTimeoutResponse.fromJSON)
	}
    static async updateTerminalReuseEnabled(request: proto.isaac.BooleanRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateTerminalReuseEnabled", request, proto.isaac.BooleanRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async getAvailableTerminalProfiles(request: proto.isaac.EmptyRequest): Promise<proto.isaac.TerminalProfiles> {
		return this.makeUnaryRequest("getAvailableTerminalProfiles", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.TerminalProfiles.fromJSON)
	}
    static subscribeToState(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.State>): ()=>void {
		return this.makeStreamingRequest("subscribeToState", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.State.fromJSON, callbacks)
	}
    static async toggleFavoriteModel(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("toggleFavoriteModel", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async resetState(request: proto.isaac.ResetStateRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("resetState", request, proto.isaac.ResetStateRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async togglePlanActModeProto(request: proto.isaac.TogglePlanActModeRequest): Promise<proto.isaac.Boolean> {
		return this.makeUnaryRequest("togglePlanActModeProto", request, proto.isaac.TogglePlanActModeRequest.toJSON, proto.isaac.Boolean.fromJSON)
	}
    static async updateAutoApprovalSettings(request: proto.isaac.AutoApprovalSettingsRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateAutoApprovalSettings", request, proto.isaac.AutoApprovalSettingsRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateSettings(request: proto.isaac.UpdateSettingsRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateSettings", request, proto.isaac.UpdateSettingsRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateSettingsCli(request: proto.isaac.UpdateSettingsRequestCli): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateSettingsCli", request, proto.isaac.UpdateSettingsRequestCli.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateTaskSettings(request: proto.isaac.UpdateTaskSettingsRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateTaskSettings", request, proto.isaac.UpdateTaskSettingsRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateTelemetrySetting(request: proto.isaac.TelemetrySettingRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateTelemetrySetting", request, proto.isaac.TelemetrySettingRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async captureOnboardingProgress(request: proto.isaac.OnboardingProgressRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("captureOnboardingProgress", request, proto.isaac.OnboardingProgressRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async setWelcomeViewCompleted(request: proto.isaac.BooleanRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("setWelcomeViewCompleted", request, proto.isaac.BooleanRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateInfoBannerVersion(request: proto.isaac.Int64Request): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateInfoBannerVersion", request, proto.isaac.Int64Request.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateModelBannerVersion(request: proto.isaac.Int64Request): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateModelBannerVersion", request, proto.isaac.Int64Request.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async updateCliBannerVersion(request: proto.isaac.Int64Request): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("updateCliBannerVersion", request, proto.isaac.Int64Request.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async dismissBanner(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("dismissBanner", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async trackBannerEvent(request: proto.isaac.TrackBannerEventRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("trackBannerEvent", request, proto.isaac.TrackBannerEventRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async installIsaacCli(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("installIsaacCli", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async checkCliInstallation(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Boolean> {
		return this.makeUnaryRequest("checkCliInstallation", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Boolean.fromJSON)
	}
    static async getProcessInfo(request: proto.isaac.EmptyRequest): Promise<proto.isaac.ProcessInfo> {
		return this.makeUnaryRequest("getProcessInfo", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.ProcessInfo.fromJSON)
	}
    static async flushPendingState(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("flushPendingState", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async testOtelConnection(request: proto.isaac.EmptyRequest): Promise<proto.isaac.TestConnectionResult> {
		return this.makeUnaryRequest("testOtelConnection", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.TestConnectionResult.fromJSON)
	}
    static async testPromptUploading(request: proto.isaac.EmptyRequest): Promise<proto.isaac.TestConnectionResult> {
		return this.makeUnaryRequest("testPromptUploading", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.TestConnectionResult.fromJSON)
	}
}
export class TaskServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.TaskService"
    static async cancelTask(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("cancelTask", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async cancelBackgroundCommand(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("cancelBackgroundCommand", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async clearTask(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("clearTask", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async getTotalTasksSize(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Int64> {
		return this.makeUnaryRequest("getTotalTasksSize", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Int64.fromJSON)
	}
    static async deleteTasksWithIds(request: proto.isaac.StringArrayRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("deleteTasksWithIds", request, proto.isaac.StringArrayRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async newTask(request: proto.isaac.NewTaskRequest): Promise<proto.isaac.String> {
		return this.makeUnaryRequest("newTask", request, proto.isaac.NewTaskRequest.toJSON, proto.isaac.String.fromJSON)
	}
    static async showTaskWithId(request: proto.isaac.StringRequest): Promise<proto.isaac.TaskResponse> {
		return this.makeUnaryRequest("showTaskWithId", request, proto.isaac.StringRequest.toJSON, proto.isaac.TaskResponse.fromJSON)
	}
    static async exportTaskWithId(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("exportTaskWithId", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async toggleTaskFavorite(request: proto.isaac.TaskFavoriteRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("toggleTaskFavorite", request, proto.isaac.TaskFavoriteRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async getTaskHistory(request: proto.isaac.GetTaskHistoryRequest): Promise<proto.isaac.TaskHistoryArray> {
		return this.makeUnaryRequest("getTaskHistory", request, proto.isaac.GetTaskHistoryRequest.toJSON, proto.isaac.TaskHistoryArray.fromJSON)
	}
    static async askResponse(request: proto.isaac.AskResponseRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("askResponse", request, proto.isaac.AskResponseRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async taskFeedback(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("taskFeedback", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async taskCompletionViewChanges(request: proto.isaac.Int64Request): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("taskCompletionViewChanges", request, proto.isaac.Int64Request.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async executeQuickWin(request: proto.isaac.ExecuteQuickWinRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("executeQuickWin", request, proto.isaac.ExecuteQuickWinRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async deleteAllTaskHistory(request: proto.isaac.EmptyRequest): Promise<proto.isaac.DeleteAllTaskHistoryCount> {
		return this.makeUnaryRequest("deleteAllTaskHistory", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.DeleteAllTaskHistoryCount.fromJSON)
	}
    static async explainChanges(request: proto.isaac.ExplainChangesRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("explainChanges", request, proto.isaac.ExplainChangesRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
}
export class UiServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.UiService"
    static async scrollToSettings(request: proto.isaac.StringRequest): Promise<proto.isaac.KeyValuePair> {
		return this.makeUnaryRequest("scrollToSettings", request, proto.isaac.StringRequest.toJSON, proto.isaac.KeyValuePair.fromJSON)
	}
    static async setTerminalExecutionMode(request: proto.isaac.BooleanRequest): Promise<proto.isaac.KeyValuePair> {
		return this.makeUnaryRequest("setTerminalExecutionMode", request, proto.isaac.BooleanRequest.toJSON, proto.isaac.KeyValuePair.fromJSON)
	}
    static async onDidShowAnnouncement(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Boolean> {
		return this.makeUnaryRequest("onDidShowAnnouncement", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Boolean.fromJSON)
	}
    static subscribeToAddToInput(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.String>): ()=>void {
		return this.makeStreamingRequest("subscribeToAddToInput", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.String.fromJSON, callbacks)
	}
    static subscribeToHistoryButtonClicked(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToHistoryButtonClicked", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON, callbacks)
	}
    static subscribeToChatButtonClicked(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToChatButtonClicked", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON, callbacks)
	}
    static subscribeToAccountButtonClicked(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToAccountButtonClicked", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON, callbacks)
	}
    static subscribeToSettingsButtonClicked(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToSettingsButtonClicked", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON, callbacks)
	}
    static subscribeToWorktreesButtonClicked(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToWorktreesButtonClicked", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON, callbacks)
	}
    static subscribeToPartialMessage(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.IsaacMessage>): ()=>void {
		return this.makeStreamingRequest("subscribeToPartialMessage", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.IsaacMessage.fromJSON, callbacks)
	}
    static async initializeWebview(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("initializeWebview", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static subscribeToRelinquishControl(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.Empty>): ()=>void {
		return this.makeStreamingRequest("subscribeToRelinquishControl", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON, callbacks)
	}
    static subscribeToShowWebview(request: proto.isaac.EmptyRequest, callbacks: Callbacks<proto.isaac.ShowWebviewEvent>): ()=>void {
		return this.makeStreamingRequest("subscribeToShowWebview", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.ShowWebviewEvent.fromJSON, callbacks)
	}
    static async getWebviewHtml(request: proto.isaac.EmptyRequest): Promise<proto.isaac.String> {
		return this.makeUnaryRequest("getWebviewHtml", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.String.fromJSON)
	}
    static async openUrl(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("openUrl", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async openWalkthrough(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("openWalkthrough", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
    static async githubCopilotLogin(request: proto.isaac.EmptyRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("githubCopilotLogin", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
}
export class WebServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.WebService"
    static async checkIsImageUrl(request: proto.isaac.StringRequest): Promise<proto.isaac.IsImageUrl> {
		return this.makeUnaryRequest("checkIsImageUrl", request, proto.isaac.StringRequest.toJSON, proto.isaac.IsImageUrl.fromJSON)
	}
    static async fetchOpenGraphData(request: proto.isaac.StringRequest): Promise<proto.isaac.OpenGraphData> {
		return this.makeUnaryRequest("fetchOpenGraphData", request, proto.isaac.StringRequest.toJSON, proto.isaac.OpenGraphData.fromJSON)
	}
    static async openInBrowser(request: proto.isaac.StringRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("openInBrowser", request, proto.isaac.StringRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
}
export class WorktreeServiceClient extends ProtoBusClient {
	static override serviceName: string = "isaac.WorktreeService"
    static async listWorktrees(request: proto.isaac.EmptyRequest): Promise<proto.isaac.WorktreeList> {
		return this.makeUnaryRequest("listWorktrees", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.WorktreeList.fromJSON)
	}
    static async createWorktree(request: proto.isaac.CreateWorktreeRequest): Promise<proto.isaac.WorktreeResult> {
		return this.makeUnaryRequest("createWorktree", request, proto.isaac.CreateWorktreeRequest.toJSON, proto.isaac.WorktreeResult.fromJSON)
	}
    static async deleteWorktree(request: proto.isaac.DeleteWorktreeRequest): Promise<proto.isaac.WorktreeResult> {
		return this.makeUnaryRequest("deleteWorktree", request, proto.isaac.DeleteWorktreeRequest.toJSON, proto.isaac.WorktreeResult.fromJSON)
	}
    static async switchWorktree(request: proto.isaac.SwitchWorktreeRequest): Promise<proto.isaac.WorktreeResult> {
		return this.makeUnaryRequest("switchWorktree", request, proto.isaac.SwitchWorktreeRequest.toJSON, proto.isaac.WorktreeResult.fromJSON)
	}
    static async getAvailableBranches(request: proto.isaac.EmptyRequest): Promise<proto.isaac.BranchList> {
		return this.makeUnaryRequest("getAvailableBranches", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.BranchList.fromJSON)
	}
    static async getWorktreeDefaults(request: proto.isaac.EmptyRequest): Promise<proto.isaac.WorktreeDefaults> {
		return this.makeUnaryRequest("getWorktreeDefaults", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.WorktreeDefaults.fromJSON)
	}
    static async getWorktreeIncludeStatus(request: proto.isaac.EmptyRequest): Promise<proto.isaac.WorktreeIncludeStatus> {
		return this.makeUnaryRequest("getWorktreeIncludeStatus", request, proto.isaac.EmptyRequest.toJSON, proto.isaac.WorktreeIncludeStatus.fromJSON)
	}
    static async createWorktreeInclude(request: proto.isaac.CreateWorktreeIncludeRequest): Promise<proto.isaac.WorktreeResult> {
		return this.makeUnaryRequest("createWorktreeInclude", request, proto.isaac.CreateWorktreeIncludeRequest.toJSON, proto.isaac.WorktreeResult.fromJSON)
	}
    static async checkoutBranch(request: proto.isaac.CheckoutBranchRequest): Promise<proto.isaac.WorktreeResult> {
		return this.makeUnaryRequest("checkoutBranch", request, proto.isaac.CheckoutBranchRequest.toJSON, proto.isaac.WorktreeResult.fromJSON)
	}
    static async mergeWorktree(request: proto.isaac.MergeWorktreeRequest): Promise<proto.isaac.MergeWorktreeResult> {
		return this.makeUnaryRequest("mergeWorktree", request, proto.isaac.MergeWorktreeRequest.toJSON, proto.isaac.MergeWorktreeResult.fromJSON)
	}
    static async trackWorktreeViewOpened(request: proto.isaac.TrackWorktreeViewOpenedRequest): Promise<proto.isaac.Empty> {
		return this.makeUnaryRequest("trackWorktreeViewOpened", request, proto.isaac.TrackWorktreeViewOpenedRequest.toJSON, proto.isaac.Empty.fromJSON)
	}
}
